# Generated by Django 5.2.10 on 2026-01-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_id', models.CharField(db_index=True, max_length=15)),
                ('time_bucket', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('score', models.IntegerField()),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('reasons_json', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['h3_id', 'time_bucket'], name='safety_risk_h3_id_5c3d1c_idx')],
                'unique_together': {('h3_id', 'time_bucket')},
            },
        ),
    ]
