# Generated by Django 5.2.10 on 2026-01-09 03:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('crime_reports', 'Crime Reports'), ('official_alerts', 'Official Alerts'), ('environment', 'Environment')], max_length=50)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ingest.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='AlertItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('severity', models.IntegerField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('h3_id', models.CharField(db_index=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.datasource')),
            ],
            options={
                'indexes': [models.Index(fields=['h3_id', 'published_at'], name='ingest_aler_h3_id_0dc254_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnvMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('h3_id', models.CharField(db_index=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.datasource')),
            ],
            options={
                'indexes': [models.Index(fields=['h3_id', 'metric'], name='ingest_envm_h3_id_bf1767_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('severity', models.IntegerField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('h3_id', models.CharField(db_index=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.datasource')),
            ],
            options={
                'indexes': [models.Index(fields=['h3_id', 'occurred_at'], name='ingest_inci_h3_id_80749a_idx')],
            },
        ),
    ]
